eLearning/eLearning.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eLearning.Application.AccountServices;
using eLearning.Application.AccountServices.Dtos;
using Microsoft.AspNetCore.Mvc;

namespace eLearning.Web.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountService _service;

        public AccountController(IAccountService service)
        {
            _service = service;
        }
        [HttpGet]
        public async Task<IActionResult> Authencation()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Authencation(LoginRequest request)
        {
            var login = await _service.Login(request);
            if (!login)
            {
                return RedirectToAction("Authencation");
            }
            return RedirectToAction("CreateCource", "Course");
        }
    }
}

eLearning/eLearning.Web/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eLearning.Application.CourseServices;
using eLearning.Application.CourseServices.Dto;
using eLearning.Application.FileServices;
using eLearning.Application.FileServices.Dtos;
using eLearning.Application.TeacherServices;
using eLearning.Common;
using eLearning.Web.Helper;
using Microsoft.AspNetCore.Mvc;

namespace eLearning.Web.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _service;
        private readonly IFileService _fileService;
        private readonly ITeacherService _teacherService;

        public CourseController(ICourseService service, IFileService fileService, ITeacherService teacherService)
        {
            this._service = service;
            this._fileService = fileService;
            this._teacherService = teacherService;
        }
        [HttpGet]
        public async Task<IActionResult> GetCources([FromQuery] int? page = 1,[FromQuery] int? pageSize = 10)
        {
            var model = await _service.GetAllPaging(page, pageSize);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> CreateCource()
        {
            return View(await _teacherService.GetAll());
        }
        [HttpPost]
        public async Task<IActionResult> CreateCource([FromForm] AddCourseRequest request)
        {
            var course = await _service.AddCourse(request);
            if(Request.Form.Files?.FirstOrDefault() != null)
            {
                var file = Request.Form.Files.FirstOrDefault();
                string fileName = await file.ToUpload();
                var addFile = new AddFileRequest()
                {
                    FileType = EnumFile.Course,
                    IdMapping = course.Id,
                    Name = fileName
                };
                await _fileService.CreateFile(addFile);
            }
            return RedirectToAction("GetCources", new { page = 1,pageSize = 10 });
        }
        
        [HttpGet]
        public async Task<IActionResult> GetCource([FromQuery] Guid id)
        {
            var model = await _service.GetById(id);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteCourse([FromQuery] Guid id)
        {
            await _service.DeleteCourse(id);
            return RedirectToAction("GetCources", new { page = 1, pageSize = 10 });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCourse([FromForm] UpdateCourseRequest request)
        {
            await _service.UpdateCourse(request);
            return RedirectToAction("GetCourse", new { id = request.Id });
        }
    }
}

eLearning/eLearning.Web/Controllers/LessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eLearning.Application.CourseServices;
using eLearning.Application.LessionServices;
using eLearning.Application.LessionServices.Dtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

namespace eLearning.Web.Controllers
{
    public class LessionController : Controller
    {
        private readonly ILessionService _service;
        private readonly ICourseService _courseService;

        public LessionController(
            ILessionService service,
            ICourseService courseService)
        {
            _service = service;
            _courseService = courseService;
        }

        [HttpGet]
        public async Task<IActionResult> AddLession([FromQuery] Guid id)
        {
            var course = await _courseService.GetById(id);
            return View(course);
        }

        [HttpPost]
        public async Task<IActionResult> AddLession(AddLessionRequest request)
        {
            var result = await _service.AddLession(request);
            if (result is null)
            {
                return RedirectToAction("CreateLession");
            }
            return RedirectToAction("GetCource", "Course", new RouteValueDictionary
            {
                {"id",request.CourseId }

            });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteLession([FromQuery] Guid id, [FromQuery] Guid courseId)
        {
            await _service.DeleteLession(id);
            return RedirectToAction("GetCourse", "Course", new { id = courseId });
        }

    }
}

eLearning/eLearning.Web/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eLearning.Application.TeacherServices;
using Microsoft.AspNetCore.Mvc;

namespace eLearning.Web.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherService _service;

        public TeacherController(ITeacherService service)
        {
            _service = service;
        }
        public async Task<IActionResult> ChildTeachers()
        {
            var model = (await _service.GetAll()).ToList();
            return PartialView("_ChildTeacher", model);
        }
        [HttpGet]
        public async Task<IActionResult> GetTeachers()
        {
            var model = await _service.GetAll();
            return View(model);
        }
    }
}

eLearning/eLearning.Web/Pages/Shared/_ChildTeachers.cshtml
@using eLearning.Core.Entities
@model IEnumerable<Teacher>
<div class="form-group">
    <h4 class="text-muted m-b-15 f-s-12">Teacher</h4>
    <select class="form-control" name="TeacherId">
        @foreach (var tea in Model)
        {
            <option value="@tea.Id">@tea.Name</option>
        }
    </select>
</div>

eLearning/eLearning.Web/Views/Course/CreateCource.cshtml
@using eLearning.Core.Entities
@model IEnumerable<Teacher>

@{
    ViewData["Title"] = "CreateCource";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-title">
                <h4>Create Course</h4>

            </div>
            <div class="card-body">
                <div class="basic-form">
                    <form asp-action="CreateCource" asp-controller="Course" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <h4 class="text-muted m-b-15 f-s-12">Name</h4>
                            <input type="text" class="form-control input-flat " placeholder="Enter course name" name="Name">
                        </div>
                        <div class="form-group">
                            <h4 class="text-muted m-b-15 f-s-12">Order</h4>
                            <input type="number" class="form-control input-flat" placeholder="Order" name="Order">
                        </div>
                        <div class="form-group">
                            <h4 class="text-muted m-b-15 f-s-12">Description</h4>
                            <textarea name="Description"></textarea>
                            <script>
                                CKEDITOR.replace('Description');
                            </script>
                        </div>
                        <div class="form-group">
                            <h4 class="text-muted m-b-15 f-s-12">Image</h4>
                            <input type="file" class="form-control input-flat" placeholder="Input Rounded" name="File">
                        </div>
                        <div class="form-group">
                            <h4 class="text-muted m-b-15 f-s-12">Type</h4>
                            <select class="form-control" name="Group">
                                <option value="1">Grammar</option>
                                <option value="2">Tutorial</option>
                            </select>
                        </div>
                        @await Html.PartialAsync("~/Pages/Shared/_ChildTeachers.cshtml", Model)
                        
                        <button type="submit" class="btn btn-primary btn-flat">Create Course</button>
                        <button class="btn btn-danger btn-flat">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

eLearning/eLearning.Web/Views/Course/GetCource.cshtml
@{
    ViewData["Title"] = "GetCource";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}
@using eLearning.Common;
@using eLearning.Core.Entities
@model Course
<script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-title">
                <h4>Update Course</h4>
            </div>
            <div class="card-body">
                <div class="basic-form">
                    <form asp-action="UpdateCourse" asp-controller="Course" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <h4 class="text-muted m-b-15 f-s-12">Name</h4>
                            <input type="text" class="form-control input-flat " placeholder="Enter course name" name="Name" value="@Model.Name">
                            <input type="text" class="form-control input-flat " placeholder="Enter course name" hidden name="Id" value="@Model.Id">
                        </div>
                        <div class="form-group">
                            <h4 class="text-muted m-b-15 f-s-12">Order</h4>
                            <input type="number" class="form-control input-flat" placeholder="Order" name="Order" value="@Model.Order">
                        </div>
                        <div class="form-group">
                            <h4 class="text-muted m-b-15 f-s-12">Description</h4>
                            <textarea name="Description"></textarea>
                            <script>
                                CKEDITOR.replace('Description', {

                                });
                            </script>
                        </div>
                        <div class="form-group">
                            <h4 class="text-muted m-b-15 f-s-12">Image</h4>
                            <input type="file" class="form-control input-flat" placeholder="Input Rounded" name="File">
                        </div>
                        <div class="form-group">
                            <h4 class="text-muted m-b-15 f-s-12">Type</h4>
                            <select class="form-control" name="Group">
                                <option value="1">Grammar</option>
                                <option value="2">Tutorial</option>
                            </select>
                        </div>
                        @* @await Html.PartialAsync("~/Pages/Shared/_ChildTeachers.cshtml", Model)*@
                        <button type="submit" class="btn btn-primary btn-flat">Update Course</button>
                        <button class="btn btn-danger btn-flat">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-title">
                <h4>Lessions in Course </h4>
            </div>
            <div class="card-body">
                <a class="btn btn-primary btn-flat" href="/Lession/AddLession?id=@Model.Id">Create Lession in Course</a>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Date</th>
                                <th>Action</th>
                                @{ int orderL = 1;}
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var lession in Model.Lessions)
                            {
                                <tr>
                                    <th scope="row">@(orderL++)</th>
                                    <td>@lession.Name</td>
                                    <td>@lession.CreatedAt.ToFormat()</td>
                                    <td>
                                        <strong><span class="ti-trash text-danger"></span></strong>
                                        <strong><span class="ti-pencil text-success"></span></strong>
                                    </td>
                                    
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

eLearning/eLearning.Web/Views/Course/GetCources.cshtml
@{
    ViewData["Title"] = "GetCources";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}
@using eLearning.Core.Entities;
@using eLearning.Common;
@model Pagination<Course>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-title">
                <h4>Courses</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Type</th>
                                <th>Teacher</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int order = 1;
                            }
                            @foreach (var course in Model.PageData)
                            {
                                <tr>
                                    <td scope="row">@order</td>
                                    <td><strong>@course.Name</strong></td>
                                    @if (course.Group == EnumCourseGroup.Grammar)
                                    {


                                        <td><span class="badge badge-primary">Grammar</span></td>
                                    }
                                    else
                                    {
                                        <td><span class="badge badge-success">Tutorial</span></td>
                                    }
                                    <td>@course.Teacher.Name</td>
                                    <td><strong>@course.CreatedAt.ToFormat()</strong></td>
                                    <td>
                                        <a href="/Course/DeleteCourse?id=@course.Id"><strong><span class="ti-trash text-danger"></span></strong></a>
                                        <a href="/Course/GetCource?id=@course.Id"><strong><span class="ti-pencil text-success"></span></strong></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

eLearning/eLearning.Web/Views/Lession/AddLession.cshtml
@{
    ViewData["Title"] = "AddLession";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}

@using eLearning.Core.Entities
@model Course
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-title">
                <h4>Create Lession in Course</h4>
            </div>
            <div class="card-body">
                <div class="basic-elements">
                    <form asp-action="AddLession" asp-controller="Lession" method="post">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Course</label>
                                    <input class="form-control" type="text" value="@Model.Name" readonly="">
                                    <input class="form-control" type="text" value="@Model.Id" hidden name="CourseId">
                                </div>
                                <div class="form-group">
                                    <label>Lession name</label>
                                    <input type="text" class="form-control" name="Name">
                                </div>
                                <div class="form-group">
                                    <label>Video url</label>
                                    <input class="form-control" type="text" name="VideoUrl">
                                </div>
                                <div class="form-group">
                                    <label>Lession Content</label>
                                    <textarea name="Content"></textarea>
                                    <script>
                                        CKEDITOR.replace('Content');
                                    </script>
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-success btn-flat" type="submit">Create Lession</button>
                        <button class="btn btn-danger btn-flat">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>